"""
Feature verification tests — no Azure credentials required for most tests.
Tests: stock tool, guardrail logic, dynamic greeting, content safety.
"""
import os
import json
from unittest.mock import MagicMock, patch

os.environ.setdefault("AZURE_OPENAI_ENDPOINT", "https://mock.openai.azure.com/")
os.environ.setdefault("AZURE_OPENAI_API_KEY", "mock-key")
os.environ.setdefault("AZURE_OPENAI_DEPLOYMENT", "gpt-4o")

from chatbot import get_stock_price, run_tool, is_content_safe, SYSTEM_PROMPT, load_memory, save_memory, clear_memory

PASS = "PASS"
FAIL = "FAIL"

results = []

def check(label, condition, detail=""):
    status = PASS if condition else FAIL
    results.append((label, status, detail))
    icon = "+" if condition else "X"
    print(f"  [{icon}] {label}")
    if detail:
        print(f"      {detail}")


# ─────────────────────────────────────────
print("\n" + "=" * 55)
print("TEST 1: Stock Price Tool — Live Data")
print("=" * 55)

for ticker in ["AAPL", "MSFT", "TSLA"]:
    data = json.loads(get_stock_price(ticker))
    has_price = data.get("price") is not None and data.get("price", 0) > 0
    check(
        f"get_stock_price({ticker})",
        has_price,
        f"company={data.get('company')}  price={data.get('currency')} {data.get('price')}  52w_high={data.get('52w_high')}"
    )

# ─────────────────────────────────────────
print("\n" + "=" * 55)
print("TEST 2: run_tool Dispatcher")
print("=" * 55)

result = json.loads(run_tool("get_stock_price", json.dumps({"ticker": "GOOGL"})))
check("run_tool dispatches get_stock_price", result.get("price") is not None,
      f"GOOGL price: {result.get('price')}")

result_bad = json.loads(run_tool("nonexistent_tool", "{}"))
check("run_tool handles unknown tool gracefully", "error" in result_bad,
      f"returned: {result_bad}")

# ─────────────────────────────────────────
print("\n" + "=" * 55)
print("TEST 3: Guardrail — System Prompt (Layer 1)")
print("=" * 55)

check("System prompt contains finance restriction",
      "ONLY answer questions related to" in SYSTEM_PROMPT)

check("System prompt defines rejection message",
      "I'm a finance assistant and can only help with finance-related topics" in SYSTEM_PROMPT)

check("System prompt mentions stock tool usage",
      "get_stock_price" in SYSTEM_PROMPT)

check("System prompt blocks investment advice",
      "Do not give specific investment advice" in SYSTEM_PROMPT)

# ─────────────────────────────────────────
print("\n" + "=" * 55)
print("TEST 4: Content Safety (Layer 2)")
print("=" * 55)

safe, reason = is_content_safe("What is the P/E ratio of Apple stock?")
check("Finance question passes when CS not configured", safe, f"reason: {reason}")

# ─────────────────────────────────────────
print("\n" + "=" * 55)
print("TEST 5: Dynamic Greeting (mocked)")
print("=" * 55)

mock_greeting = "Hello! I'm FinanceBot, your AI-powered finance assistant. I can look up live stock prices and answer your finance questions — how can I help?"

with patch("chatbot.client") as mock_client:
    mock_response = MagicMock()
    mock_response.choices[0].message.content = mock_greeting
    mock_client.chat.completions.create.return_value = mock_response

    from chatbot import client as c
    resp = mock_client.chat.completions.create(
        model="gpt-4o",
        messages=[
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": "Greet the user..."},
        ],
        max_tokens=100,
        temperature=0.9,
    )
    greeting = resp.choices[0].message.content

check("Greeting generated by model (not hardcoded)", greeting == mock_greeting,
      f'"{greeting[:80]}..."')
check("Greeting is not empty", len(greeting) > 10)
check("API called with system prompt", mock_client.chat.completions.create.called)

# ─────────────────────────────────────────
print("\n" + "=" * 55)
print("TEST 6: Persistent Memory (JSON)")
print("=" * 55)

# Start clean
clear_memory()
check("clear_memory removes file", not __import__("os").path.exists("memory.json"))

# Save some messages
fake_history = [
    {"role": "system", "content": SYSTEM_PROMPT},
    {"role": "user", "content": "What is a P/E ratio?"},
    {"role": "assistant", "content": "P/E ratio is price divided by earnings per share."},
]
save_memory(fake_history)
check("save_memory creates memory.json", __import__("os").path.exists("memory.json"))

# Load it back — system message should be excluded from the file
loaded = load_memory()
check("load_memory returns saved messages", len(loaded) == 2,
      f"loaded {len(loaded)} messages (system excluded)")

check("loaded content is correct (user message)",
      loaded[0]["role"] == "user" and "P/E ratio" in loaded[0]["content"])

check("loaded content is correct (assistant message)",
      loaded[1]["role"] == "assistant" and "earnings" in loaded[1]["content"])

# Clear and verify gone
clear_memory()
check("clear_memory wipes the file", not __import__("os").path.exists("memory.json"))

# load_memory returns empty list when no file exists
check("load_memory returns [] when no file", load_memory() == [])

# ─────────────────────────────────────────
print("\n" + "=" * 55)
passed = sum(1 for _, s, _ in results if s == PASS)
failed = sum(1 for _, s, _ in results if s == FAIL)
print(f"Results: {passed} passed, {failed} failed out of {len(results)} tests")
print("=" * 55)
if failed:
    print("\nFailed tests:")
    for label, status, detail in results:
        if status == FAIL:
            print(f"  - {label}: {detail}")
